### ISSUE TITLE
fileprovider.cpp depends on Settings class from kdwsdl2pp

### ISSUE THREAD

**Issue by winterz** [cornelius/libkode#4]
common/fileprovider.cpp includes settings.h and uses the Settings class from kdwsdl2cpp

**Comment by martonmiklos** [comment]
Thanks @winterz ! I will try to find some time to add this repo back to the kode and these problems (like #2 ) will fall out then.

**Comment by martonmiklos** [comment]
@winterz would it be acceptable for you (and KDAB) to replace the Settings calls with passing the three parameters (importPathList, useLocalFilesOnly, and the SSL configuration) via the FileProvider constructor?

**Comment by dfaure-kdab** [comment]
Yes this makes sense, for the first two.

For the SSL configuration, how about just calling QSslConfiguration::setDefaultConfiguration in KDSoap (and other users of this code)? Then the QNAM usage in FileProvider will just inherit that configuration automatically.

Since it's already a global configuration in Settings::self(), it's not like we support different SSL configuration for each FileProvider anyway, so we might as well use the global QSslConfiguration.
This is more flexible because more things can be set in that object without having to add parameters to FileProvider.

**Comment by martonmiklos** [comment]
> For the SSL configuration, how about just calling QSslConfiguration::setDefaultConfiguration in KDSoap (and other users of this code)? Then the QNAM usage in FileProvider will just inherit that configuration automatically.

Good idea, I will do this way!
